signfs: add missing include for major()/minor() since glibc 2.28
if we do not include sysmacros.h, we get these errors with glibc >= 2.28:

signfs.c: In function ‘print_fileinfo’:
signfs.c:102:23: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
  102 |   sprintf(tmp,"%d,%d",major(data->rdev),minor(data->rdev));
      |                       ^~~~~
signfs.c:102:41: warning: implicit declaration of function ‘minor’ [-Wimplicit-function-declaration]
  102 |   sprintf(tmp,"%d,%d",major(data->rdev),minor(data->rdev));
      |                                         ^~~~~
gcc -g   -c -o structure.o structure.c
gcc -o signfs main.o signfs.o structure.o -L. -ltools
/usr/bin/ld: signfs.o: in function `print_fileinfo':
/home/eric/tmp/flxutils/signfs/signfs.c:102: undefined reference to `minor'
/usr/bin/ld: /home/eric/tmp/flxutils/signfs/signfs.c:102: undefined reference to `major'
collect2: error: ld returned 1 exit status