init: add missing include for major()/minor() since glibc 2.28
The following build error happens on recent glibc which impose the use
of sysmacros.h to get the definitions:

init.c: In function ‘mknod_chown’:
init.c:763:24: warning: implicit declaration of function ‘makedev’ [-Wimplicit-function-declaration]
  763 |  if (mknod(name, mode, makedev(major, minor)) == -1 && chmod(name, mode) == -1) {