flx: add missing include for major()/minor() since glibc 2.28
The following build error happens on recent glibc which impose the use
of sysmacros.h to get the definitions:

  /usr/bin/ld: fct1.o: in function `build_line':
  fct1.c:(.text+0xfe8): undefined reference to `minor'
  /usr/bin/ld: fct1.c:(.text+0xff7): undefined reference to `major'

Not sure about other OSes though.