init: add missing include for mknod() and mkdir() since glibc 2.28
we need to include stat.h, otherwise we get this error:

mkdev.c: In function ‘mknod_chown’:
mkdev.c:105:9: warning: implicit declaration of function ‘mknod’ [-Wimplicit-function-declaration]
  105 |     if (mknod(name, mode, makedev(major, minor)) == -1) {
      |         ^~~~~
mkdev.c: In function ‘main’:
mkdev.c:461:10: warning: implicit declaration of function ‘mkdir’ [-Wimplicit-function-declaration]
  461 |      if (mkdir(cfg_args[0], mode) == -1)
      |          ^~~~~