ifenslave/Makefile: remove the duplicate "clean" rule
This fixes this harmless warning caused by a redefinition of the rule :

Makefile:11: warning: overriding recipe for target `clean'
../include/rules.make:30: warning: ignoring old recipe for target `clean'