init: add missing include for major()/minor() since glibc 2.28
if we do not include sysmacros.h, we get these errors with glibc >= 2.28:

mkdev.c: In function ‘mknod_chown’:
mkdev.c:105:9: warning: implicit declaration of function ‘mknod’ [-Wimplicit-function-declaration]
  105 |     if (mknod(name, mode, makedev(major, minor)) == -1) {
      |         ^~~~~
mkdev.c:105:27: warning: implicit declaration of function ‘makedev’ [-Wimplicit-function-declaration]
  105 |     if (mknod(name, mode, makedev(major, minor)) == -1) {
      |                           ^~~~~~~
mkdev.c: In function ‘main’:
mkdev.c:461:10: warning: implicit declaration of function ‘mkdir’ [-Wimplicit-function-declaration]
  461 |      if (mkdir(cfg_args[0], mode) == -1)
      |          ^~~~~
/usr/bin/ld: /tmp/cclgjtXb.o: in function `mknod_chown.isra.0':
mkdev.c:(.text+0xac): undefined reference to `makedev'
collect2: error: ld returned 1 exit status
make: *** [../include/rules.make:21: mkdev] Error 1