init: fix missing include to define sched_yield()
otherwise we get this error:

init.c: In function ‘main’:
init.c:2395:8: warning: implicit declaration of function ‘sched_yield’; did you mean ‘SYS_sched_yield’? [-Wimplicit-function-declaration]
 2395 |        sched_yield();
      |        ^~~~~~~~~~~
      |        SYS_sched_yield